apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: <%= @name %>
    name: <%= @name %>
  name: <%= @name %>
  namespace: aurora-bootstrap
spec:
  backoffLimit: 10
  completions: 1
  parallelism: 1
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        iam.amazonaws.role: ""
      creationTimestamp: null
      labels:
        app: <%= @name %>
        job-name: <%= @name %>
        name: <%= @name %>
    spec:
      containers:      
      - env:
        image: gaorlov/aurora-bootstrap:<%= @version %>
        imagePullPolicy: Always
        name: <%= @name %>
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30